"""
### THIS FILE WAS GENERATED BY CHATGPT 5.5 (high)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from copy import deepcopy
import math
import os
import random
from typing import Callable

from PIL import Image, ImageDraw, ImageFilter
import numpy as np

from dataformat.dataformat import Annotation


try:
    _BILINEAR = Image.Resampling.BILINEAR
    _FLIP_LEFT_RIGHT = Image.Transpose.FLIP_LEFT_RIGHT
    _ROTATE_90 = Image.Transpose.ROTATE_90
    _ROTATE_270 = Image.Transpose.ROTATE_270
except AttributeError:
    _BILINEAR = Image.BILINEAR
    _FLIP_LEFT_RIGHT = Image.FLIP_LEFT_RIGHT
    _ROTATE_90 = Image.ROTATE_90
    _ROTATE_270 = Image.ROTATE_270


# ---------------------------------------------------------------------------
# Annotation helpers
# ---------------------------------------------------------------------------

_EPS = 1e-12


def _clone_annotation(annotation: Annotation) -> Annotation:
    """
    Never mutate the input annotation in place.
    """
    return deepcopy(annotation)


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def _coerce_fill(image: Image.Image, fill):
    """
    Coerce fill values so they work for RGB, RGBA, L, etc.
    """
    bands = image.getbands()
    n_bands = len(bands)

    if isinstance(fill, int):
        if n_bands == 1:
            return fill
        if "A" in bands:
            return tuple([fill] * (n_bands - 1) + [255])
        return tuple([fill] * n_bands)

    if isinstance(fill, tuple):
        if n_bands == 1:
            return int(fill[0])

        if len(fill) == n_bands:
            return fill

        if len(fill) > n_bands:
            return fill[:n_bands]

        missing = n_bands - len(fill)
        if "A" in bands:
            return tuple(fill) + tuple([255] * missing)

        return tuple(fill) + tuple([fill[-1]] * missing)

    return fill


def _bbox_to_xyxy(bbox) -> tuple[float, float, float, float]:
    """
    Convert normalized cx, cy, w, h bbox to normalized x1, y1, x2, y2.
    Coordinates are allowed to be outside [0, 1] after augmentation.
    """
    x1 = bbox.cx - bbox.w / 2.0
    y1 = bbox.cy - bbox.h / 2.0
    x2 = bbox.cx + bbox.w / 2.0
    y2 = bbox.cy + bbox.h / 2.0
    return x1, y1, x2, y2


def _xyxy_to_cxcywh(
    x1: float,
    y1: float,
    x2: float,
    y2: float,
) -> tuple[float, float, float, float]:
    return (
        (x1 + x2) / 2.0,
        (y1 + y2) / 2.0,
        max(0.0, x2 - x1),
        max(0.0, y2 - y1),
    )


def _set_bbox_from_xyxy(bbox, xyxy: tuple[float, float, float, float]) -> None:
    cx, cy, w, h = _xyxy_to_cxcywh(*xyxy)
    bbox.cx = float(cx)
    bbox.cy = float(cy)
    bbox.w = float(w)
    bbox.h = float(h)


def _set_bbox_values(
    bbox,
    cx: float,
    cy: float,
    w: float,
    h: float,
) -> None:
    bbox.cx = float(cx)
    bbox.cy = float(cy)
    bbox.w = float(w)
    bbox.h = float(h)


def _clip_xyxy_to_unit_square(
    x1: float,
    y1: float,
    x2: float,
    y2: float,
) -> tuple[float, float, float, float] | None:
    """
    Clip a bbox to the image.

    Returns None if the bbox has no visible area at all.
    """
    if x1 > x2:
        x1, x2 = x2, x1
    if y1 > y2:
        y1, y2 = y2, y1

    clipped_x1 = max(0.0, x1)
    clipped_y1 = max(0.0, y1)
    clipped_x2 = min(1.0, x2)
    clipped_y2 = min(1.0, y2)

    if clipped_x2 <= clipped_x1 or clipped_y2 <= clipped_y1:
        return None

    return clipped_x1, clipped_y1, clipped_x2, clipped_y2


def _project_ray_to_image_border(
    start_x: float,
    start_y: float,
    target_x: float,
    target_y: float,
) -> tuple[float, float]:
    """
    Project from a visible button center toward an out-of-frame fastener center.

    The returned point is on the image border and represents the direction of
    the missing fastener. This is used with w = h = 0 for the fastener bbox.
    """
    start_x = _clamp(start_x)
    start_y = _clamp(start_y)

    dx = target_x - start_x
    dy = target_y - start_y

    if abs(dx) < _EPS and abs(dy) < _EPS:
        return start_x, start_y

    candidates: list[tuple[float, float, float]] = []

    if abs(dx) >= _EPS:
        for border_x in (0.0, 1.0):
            t = (border_x - start_x) / dx
            if t >= -_EPS:
                y = start_y + t * dy
                if -_EPS <= y <= 1.0 + _EPS:
                    candidates.append((max(0.0, t), border_x, _clamp(y)))

    if abs(dy) >= _EPS:
        for border_y in (0.0, 1.0):
            t = (border_y - start_y) / dy
            if t >= -_EPS:
                x = start_x + t * dx
                if -_EPS <= x <= 1.0 + _EPS:
                    candidates.append((max(0.0, t), _clamp(x), border_y))

    if candidates:
        _, x, y = min(candidates, key=lambda item: item[0])
        return x, y

    return _clamp(target_x), _clamp(target_y)


def _transform_annotation_boxes(
    annotation: Annotation,
    bbox_transform: Callable[[object], tuple[float, float, float, float]],
) -> Annotation:
    """
    Apply a bbox transform to every pair in an Annotation.

    Rules implemented here:

    1. Labels are deep-copied first; the input Annotation is never modified.
    2. If the transformed button bbox has no visible area in the image, remove
       the entire pair, including the corresponding fastener.
    3. If the button remains visible but the fastener has no visible area, keep
       the pair, but place the fastener center on the image border in the
       direction of the transformed fastener, with w = h = 0.
    4. If a bbox is partially visible, clip it to the image.
    5. The existing `visible` field is not used to make decisions. It is only
       updated for consistency after the geometric transform.
    """
    new_annotation = _clone_annotation(annotation)
    new_pairs = []

    for pair in new_annotation.cloth.pairs:
        button_xyxy = bbox_transform(pair.button.bbox)
        fastener_xyxy = bbox_transform(pair.fastener.bbox)

        clipped_button = _clip_xyxy_to_unit_square(*button_xyxy)

        if clipped_button is None:
            # Button has gone fully out of the image.
            # The fastener for this pair is removed with the button.
            continue

        _set_bbox_from_xyxy(pair.button.bbox, clipped_button)
        pair.button.visible = True

        clipped_fastener = _clip_xyxy_to_unit_square(*fastener_xyxy)

        if clipped_fastener is None:
            # Fastener is fully out of frame, but the button is still visible.
            # Keep directional information by projecting the fastener center to
            # the image border and using a null bbox size.
            button_cx = pair.button.bbox.cx
            button_cy = pair.button.bbox.cy
            fastener_cx, fastener_cy, _, _ = _xyxy_to_cxcywh(*fastener_xyxy)

            border_x, border_y = _project_ray_to_image_border(
                button_cx,
                button_cy,
                fastener_cx,
                fastener_cy,
            )

            _set_bbox_values(
                pair.fastener.bbox,
                cx=border_x,
                cy=border_y,
                w=0.0,
                h=0.0,
            )
            pair.fastener.visible = False
        else:
            _set_bbox_from_xyxy(pair.fastener.bbox, clipped_fastener)
            pair.fastener.visible = True

        new_pairs.append(pair)

    new_annotation.cloth.pairs = new_pairs
    return new_annotation


def _annotation_reference_points(annotation: Annotation) -> list[tuple[float, float]]:
    """
    Return normalized center points for buttons and fasteners.

    Fasteners with w = h = 0 are intentionally included because they can encode
    an out-of-frame direction.
    """
    points = []

    for pair in annotation.cloth.pairs:
        points.append((pair.button.bbox.cx, pair.button.bbox.cy))
        points.append((pair.fastener.bbox.cx, pair.fastener.bbox.cy))

    return points


def _rect_contains_point(
    point: tuple[float, float],
    rect: tuple[float, float, float, float],
) -> bool:
    px, py = point
    x1, y1, x2, y2 = rect

    if x1 > x2:
        x1, x2 = x2, x1
    if y1 > y2:
        y1, y2 = y2, y1

    return x1 <= px <= x2 and y1 <= py <= y2


# ---------------------------------------------------------------------------
# Base classes
# ---------------------------------------------------------------------------

class Transform(ABC):
    def __init__(self):
        self.current_epoch = 0

    def set_epoch(self, epoch: int):
        self.current_epoch = max(0, int(epoch))

    @abstractmethod
    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        raise NotImplementedError


class ComposeWithLabels(Transform):
    def __init__(self, transformations):
        super().__init__()
        self.transformations = list(transformations)

    def set_epoch(self, epoch: int):
        super().set_epoch(epoch)

        for transformation in self.transformations:
            if hasattr(transformation, "set_epoch"):
                transformation.set_epoch(epoch)

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        for transformation in self.transformations:
            image, labels = transformation(image, labels)
        return image, labels


class ComposeWrapper(Transform):
    """
    Wrap an image-only transform so it can be used in a label-aware pipeline.
    """
    def __init__(self, transformation):
        super().__init__()
        self.transformation = transformation

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        image = self.transformation(image)
        return image, _clone_annotation(labels)


# ---------------------------------------------------------------------------
# Pixel-only transforms
# ---------------------------------------------------------------------------

class RandomSafeErasing(Transform):
    def __init__(
        self,
        p: float = 0.2,
        min_width: float = 0.02,
        max_width: float = 0.2,
        min_height: float = 0.02,
        max_height: float = 0.2,
        safety_radius: float = 0.04,
        max_trials: int = 20,
        fill=(0, 0, 0),
    ):
        super().__init__()
        self.p = p
        self.min_width = min_width
        self.max_width = max_width
        self.min_height = min_height
        self.max_height = max_height
        self.safety_radius = safety_radius
        self.max_trials = max_trials
        self.fill = fill

    def _is_safe_rectangle(
        self,
        points_to_avoid: list[tuple[float, float]],
        x0: float,
        y0: float,
        x1: float,
        y1: float,
        W: int,
        H: int,
    ) -> bool:
        radius_x = self.safety_radius * W
        radius_y = self.safety_radius * H

        for normalized_x, normalized_y in points_to_avoid:
            px = normalized_x * W
            py = normalized_y * H

            safe_x0 = px - radius_x
            safe_y0 = py - radius_y
            safe_x1 = px + radius_x
            safe_y1 = py + radius_y

            overlaps = not (
                x1 < safe_x0
                or x0 > safe_x1
                or y1 < safe_y0
                or y0 > safe_y1
            )

            if overlaps:
                return False

        return True

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        new_labels = _clone_annotation(labels)

        if random.random() > self.p:
            return image, new_labels

        W, H = image.size
        out = image.copy()
        draw = ImageDraw.Draw(out)

        points_to_avoid = _annotation_reference_points(new_labels)

        n_rectangles = random.randrange(1, 3)
        n_done = 0

        for _ in range(self.max_trials):
            if n_done >= n_rectangles:
                break

            erase_w = max(1, int(random.uniform(self.min_width, self.max_width) * W))
            erase_h = max(1, int(random.uniform(self.min_height, self.max_height) * H))

            erase_w = min(erase_w, W)
            erase_h = min(erase_h, H)

            x0 = random.randint(0, W - erase_w)
            y0 = random.randint(0, H - erase_h)
            x1 = x0 + erase_w
            y1 = y0 + erase_h

            if not self._is_safe_rectangle(
                points_to_avoid,
                x0,
                y0,
                x1,
                y1,
                W,
                H,
            ):
                continue

            draw.rectangle(
                [x0, y0, x1, y1],
                fill=_coerce_fill(image, self.fill),
            )
            n_done += 1

        return out, new_labels


class RandomButtonErasing(Transform):
    """
    Erases a rectangle around a randomly selected button.

    Any pair whose button center is inside the erased rectangle is removed.
    This follows the requested rule: once the button is not visible, the
    corresponding fastener is removed as well.
    """
    def __init__(
        self,
        p: float = 0.25,
        min_size: float = 0.05,
        max_size: float = 0.2,
    ):
        super().__init__()
        self.p = p
        self.min_size = min_size
        self.max_size = max_size

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        new_labels = _clone_annotation(labels)

        if random.random() > self.p or len(new_labels.cloth.pairs) == 0:
            return image, new_labels

        W, H = image.size

        selected_pair = random.choice(new_labels.cloth.pairs)
        button = selected_pair.button.bbox

        center_x = button.cx * W
        center_y = button.cy * H

        erase_w = random.uniform(self.min_size, self.max_size) * W
        erase_h = random.uniform(self.min_size, self.max_size) * H

        rect = (
            center_x - erase_w / 2.0,
            center_y - erase_h / 2.0,
            center_x + erase_w / 2.0,
            center_y + erase_h / 2.0,
        )

        fill_value = random.randint(0, 160)
        fill = _coerce_fill(image, fill_value)

        out = image.copy()
        draw = ImageDraw.Draw(out)
        draw.rectangle(rect, fill=fill)

        kept_pairs = []

        for pair in new_labels.cloth.pairs:
            point = (
                pair.button.bbox.cx * W,
                pair.button.bbox.cy * H,
            )

            if _rect_contains_point(point, rect):
                continue

            kept_pairs.append(pair)

        new_labels.cloth.pairs = kept_pairs
        return out, new_labels


class RandomProgressiveFoveatedBlur(Transform):
    """
    Blur is strongest far from the buttons/fasteners and weakest near them.

    Progressive behavior:
    - call set_epoch(epoch) from the training loop
    - the maximum blur radius decreases over time
    """
    def __init__(
        self,
        p: float = 0.3,
        current_epoch: int = 0,
        initial_max_blur_radius: float = 15.0,
        final_max_blur_radius: float = 0.0,
        blur_levels: int = 6,
        keep_radius: float = 0.015,
        fade_radius: float = 0.12,
        center_jitter: float = 0.0,
        total_decay_epochs: int = 20,
        decay_every: int = 1,
        schedule: str = "cosine",
        blur_mode: str = "box",
        smoothstep: bool = True,
    ):
        super().__init__()
        self.p = p
        self.initial_max_blur_radius = initial_max_blur_radius
        self.final_max_blur_radius = final_max_blur_radius
        self.blur_levels = max(2, int(blur_levels))
        self.keep_radius = keep_radius
        self.fade_radius = fade_radius
        self.center_jitter = center_jitter
        self.total_decay_epochs = max(1, int(total_decay_epochs))
        self.decay_every = max(1, int(decay_every))
        self.schedule = schedule
        self.blur_mode = blur_mode
        self.smoothstep = smoothstep
        self.current_epoch = max(0, int(current_epoch))

        if self.fade_radius < self.keep_radius:
            raise ValueError("fade_radius must be >= keep_radius")

    def _get_progress(self) -> float:
        effective_epoch = (
            self.current_epoch // self.decay_every
        ) * self.decay_every

        t = effective_epoch / float(self.total_decay_epochs)
        return _clamp(t)

    def _get_current_max_blur_radius(self) -> float:
        t = self._get_progress()

        if self.schedule == "linear":
            factor = 1.0 - t
        elif self.schedule == "cosine":
            factor = 0.5 * (1.0 + math.cos(math.pi * t))
        else:
            raise ValueError(f"Unknown schedule: {self.schedule}")

        return (
            self.final_max_blur_radius
            + (self.initial_max_blur_radius - self.final_max_blur_radius) * factor
        )

    def _blur(self, image: Image.Image, radius: float) -> Image.Image:
        if radius <= 0.0:
            return image.copy()

        if self.blur_mode == "box":
            return image.filter(ImageFilter.BoxBlur(radius))

        if self.blur_mode == "gaussian":
            return image.filter(ImageFilter.GaussianBlur(radius))

        raise ValueError(f"Unknown blur_mode: {self.blur_mode}")

    def _build_blur_stack(
        self,
        image: Image.Image,
        current_max_blur_radius: float,
    ) -> np.ndarray:
        radii = []
        blurred_arrays = []

        for i in range(self.blur_levels):
            t = i / float(self.blur_levels - 1)
            radius = current_max_blur_radius * t
            radius_key = round(radius, 3)

            if len(radii) > 0 and abs(radius_key - radii[-1]) < 1e-6:
                blurred_arrays.append(blurred_arrays[-1])
                continue

            blurred = self._blur(image, radius)
            arr = np.asarray(blurred).astype(np.float32)

            radii.append(radius_key)
            blurred_arrays.append(arr)

        return np.stack(blurred_arrays, axis=0)

    def _compute_distance_map(
        self,
        W: int,
        H: int,
        labels: Annotation,
    ) -> np.ndarray:
        xs = np.arange(W, dtype=np.float32)[None, :]
        ys = np.arange(H, dtype=np.float32)[:, None]

        min_dist_sq = np.full((H, W), np.inf, dtype=np.float32)

        for x, y in _annotation_reference_points(labels):
            jitter_x = random.uniform(-self.center_jitter, self.center_jitter)
            jitter_y = random.uniform(-self.center_jitter, self.center_jitter)

            x = _clamp(x + jitter_x)
            y = _clamp(y + jitter_y)

            px = x * (W - 1)
            py = y * (H - 1)

            dist_sq = (xs - px) ** 2 + (ys - py) ** 2
            min_dist_sq = np.minimum(min_dist_sq, dist_sq)

        return np.sqrt(min_dist_sq)

    def _compute_blend_position_map(
        self,
        distance_map: np.ndarray,
        W: int,
        H: int,
    ) -> np.ndarray:
        base = float(min(W, H))

        keep_px = self.keep_radius * base
        fade_px = self.fade_radius * base

        if fade_px <= keep_px:
            fade_px = keep_px + 1.0

        t = (distance_map - keep_px) / (fade_px - keep_px)
        t = np.clip(t, 0.0, 1.0)

        if self.smoothstep:
            t = t * t * (3.0 - 2.0 * t)

        return t * float(self.blur_levels - 1)

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        new_labels = _clone_annotation(labels)

        if random.random() > self.p:
            return image, new_labels

        if len(new_labels.cloth.pairs) == 0:
            return image, new_labels

        W, H = image.size
        current_max_blur_radius = self._get_current_max_blur_radius()

        if current_max_blur_radius <= 0.0:
            return image, new_labels

        blur_stack = self._build_blur_stack(image, current_max_blur_radius)
        distance_map = self._compute_distance_map(W, H, new_labels)
        level_map = self._compute_blend_position_map(distance_map, W, H)

        level0 = np.floor(level_map).astype(np.int32)
        level1 = np.clip(level0 + 1, 0, self.blur_levels - 1)
        alpha = (level_map - level0).astype(np.float32)

        yy, xx = np.indices((H, W))

        if blur_stack.ndim == 4:
            pix0 = blur_stack[level0, yy, xx]
            pix1 = blur_stack[level1, yy, xx]

            out = (
                pix0 * (1.0 - alpha[..., None])
                + pix1 * alpha[..., None]
            )
        else:
            pix0 = blur_stack[level0, yy, xx]
            pix1 = blur_stack[level1, yy, xx]

            out = pix0 * (1.0 - alpha) + pix1 * alpha

        out = np.clip(out, 0, 255).astype(np.uint8)
        return Image.fromarray(out), new_labels


# ---------------------------------------------------------------------------
# Geometric transforms
# ---------------------------------------------------------------------------

class RandomHorizontalFlip(Transform):
    def __init__(self, p: float = 0.5):
        super().__init__()
        self.p = p

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        flipped = image.transpose(_FLIP_LEFT_RIGHT)

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)
            return 1.0 - x2, y1, 1.0 - x1, y2

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return flipped, new_labels


class RandomHorizontalTranslation(Transform):
    def __init__(
        self,
        p: float = 0.5,
        min: float = -0.3,
        max: float = 0.3,
        fill=(0, 0, 0),
    ):
        super().__init__()
        self.p = p
        self.min = min
        self.max = max
        self.fill = fill

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        W, H = image.size
        shift = random.uniform(self.min, self.max)
        pixel_shift = int(round(shift * W))

        translated = Image.new(
            image.mode,
            (W, H),
            _coerce_fill(image, self.fill),
        )
        translated.paste(image, (pixel_shift, 0))

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)
            return x1 + shift, y1, x2 + shift, y2

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return translated, new_labels


class RandomVerticalTranslation(Transform):
    def __init__(
        self,
        p: float = 0.5,
        min: float = -0.3,
        max: float = 0.3,
        fill=(0, 0, 0),
    ):
        super().__init__()
        self.p = p
        self.min = min
        self.max = max
        self.fill = fill

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        W, H = image.size
        shift = random.uniform(self.min, self.max)
        pixel_shift = int(round(shift * H))

        translated = Image.new(
            image.mode,
            (W, H),
            _coerce_fill(image, self.fill),
        )
        translated.paste(image, (0, pixel_shift))

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)
            return x1, y1 + shift, x2, y2 + shift

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return translated, new_labels


class RandomRotation(Transform):
    def __init__(
        self,
        p: float = 0.5,
        min_angle: float = -90.0,
        max_angle: float = 90.0,
        fill=(0, 0, 0),
    ):
        super().__init__()
        self.p = p
        self.min_angle = min_angle
        self.max_angle = max_angle
        self.fill = fill

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        W, H = image.size
        angle = random.uniform(self.min_angle, self.max_angle)

        rotated = image.rotate(
            angle,
            resample=_BILINEAR,
            expand=False,
            fillcolor=_coerce_fill(image, self.fill),
        )

        cx = W / 2.0
        cy = H / 2.0

        # Keep the same sign convention as the original implementation.
        theta = -angle * math.pi / 180.0
        cos_t = math.cos(theta)
        sin_t = math.sin(theta)

        def rotate_point(px: float, py: float) -> tuple[float, float]:
            dx = px - cx
            dy = py - cy

            new_dx = dx * cos_t - dy * sin_t
            new_dy = dx * sin_t + dy * cos_t

            return cx + new_dx, cy + new_dy

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)

            corners = [
                (x1 * W, y1 * H),
                (x2 * W, y1 * H),
                (x2 * W, y2 * H),
                (x1 * W, y2 * H),
            ]

            rotated_corners = [rotate_point(px, py) for px, py in corners]

            xs = [point[0] / W for point in rotated_corners]
            ys = [point[1] / H for point in rotated_corners]

            return min(xs), min(ys), max(xs), max(ys)

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return rotated, new_labels


class RandomSafeCrop(Transform):
    def __init__(
        self,
        p: float = 0.4,
        min_width: float = 0.7,
        max_width: float = 1.0,
        min_height: float = 0.7,
        max_height: float = 1.0,
    ):
        super().__init__()
        self.p = p
        self.min_width = min_width
        self.max_width = max_width
        self.min_height = min_height
        self.max_height = max_height

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        W, H = image.size

        crop_w = int(random.uniform(self.min_width, self.max_width) * W)
        crop_h = int(random.uniform(self.min_height, self.max_height) * H)

        crop_w = max(1, min(crop_w, W))
        crop_h = max(1, min(crop_h, H))

        if crop_w == W and crop_h == H:
            return image, _clone_annotation(labels)

        left = random.randint(0, W - crop_w)
        top = random.randint(0, H - crop_h)
        right = left + crop_w
        bottom = top + crop_h

        cropped = image.crop((left, top, right, bottom))

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)

            return (
                (x1 * W - left) / crop_w,
                (y1 * H - top) / crop_h,
                (x2 * W - left) / crop_w,
                (y2 * H - top) / crop_h,
            )

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return cropped, new_labels


class RandomZoomOut(Transform):
    def __init__(
        self,
        p: float = 0.5,
        min_scale: float = 0.7,
        max_scale: float = 1.0,
    ):
        super().__init__()
        self.p = p
        self.min_scale = min_scale
        self.max_scale = max_scale

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        W, H = image.size

        scale = random.uniform(self.min_scale, self.max_scale)

        new_W = max(1, int(scale * W))
        new_H = max(1, int(scale * H))

        if new_W == W and new_H == H:
            return image, _clone_annotation(labels)

        fill_value = random.randint(0, 80)
        fill = _coerce_fill(image, fill_value)

        resized = image.resize((new_W, new_H), _BILINEAR)

        canvas = Image.new(image.mode, (W, H), fill)

        offset_x = random.randint(0, W - new_W)
        offset_y = random.randint(0, H - new_H)

        canvas.paste(resized, (offset_x, offset_y))

        scale_x = new_W / float(W)
        scale_y = new_H / float(H)
        offset_x_norm = offset_x / float(W)
        offset_y_norm = offset_y / float(H)

        def transform_bbox(bbox):
            x1, y1, x2, y2 = _bbox_to_xyxy(bbox)

            return (
                x1 * scale_x + offset_x_norm,
                y1 * scale_y + offset_y_norm,
                x2 * scale_x + offset_x_norm,
                y2 * scale_y + offset_y_norm,
            )

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return canvas, new_labels


class RandomResize(Transform):
    def __init__(self, sizes, resample=_BILINEAR):
        super().__init__()
        self.sizes = list(sizes)
        self.resample = resample

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        size = random.choice(self.sizes)
        resized = image.resize((size, size), self.resample)

        # Labels stay unchanged because bboxes are normalized.
        return resized, _clone_annotation(labels)


# ---------------------------------------------------------------------------
# Debug transform
# ---------------------------------------------------------------------------

class SaveImage(Transform):
    """
    Debug transform.

    Saves a copy of the image with button and fastener centers/bboxes drawn.
    Does not modify the returned image or labels.
    """
    def __init__(self, directory: str = "tests", radius: int = 4):
        super().__init__()
        self.directory = directory
        self.radius = radius

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        new_labels = _clone_annotation(labels)

        os.makedirs(self.directory, exist_ok=True)

        out = image.copy()
        draw = ImageDraw.Draw(out)
        W, H = out.size

        for i, pair in enumerate(new_labels.cloth.pairs):
            button_bbox = pair.button.bbox
            fastener_bbox = pair.fastener.bbox

            self._draw_bbox(
                draw,
                button_bbox,
                W,
                H,
                outline=(255, 0, 0),
                text=f"B{i}",
            )

            self._draw_bbox(
                draw,
                fastener_bbox,
                W,
                H,
                outline=(0, 255, 0),
                text=f"F{i}",
            )

        filename = f"{random.randrange(500_000)}.png"
        out.save(os.path.join(self.directory, filename))

        return image, new_labels

    def _draw_bbox(
        self,
        draw: ImageDraw.ImageDraw,
        bbox,
        W: int,
        H: int,
        outline,
        text: str,
    ) -> None:
        cx = bbox.cx * W
        cy = bbox.cy * H

        x1 = (bbox.cx - bbox.w / 2.0) * W
        y1 = (bbox.cy - bbox.h / 2.0) * H
        x2 = (bbox.cx + bbox.w / 2.0) * W
        y2 = (bbox.cy + bbox.h / 2.0) * H

        radius = self.radius

        draw.rectangle(
            [x1, y1, x2, y2],
            outline=outline,
            width=2,
        )

        draw.ellipse(
            [cx - radius, cy - radius, cx + radius, cy + radius],
            fill=outline,
            outline=(255, 255, 255),
        )

        draw.text(
            (cx + 6, cy - 6),
            text,
            fill=outline,
        )



class RandomFastenerPartMasking(Transform):
    """
    Randomly masks image regions containing at least one fastener.

    Main purpose:
    - hide a fastener / velcro region while keeping the pair annotation
      whenever the corresponding button remains visible.
    - this forces the model to infer the full button-fastener pair from the
      visible button and surrounding context.

    Annotation rule:
    - The input Annotation is never modified in place.
    - If a button is covered by the mask, the whole pair is removed.
    - If a fastener is covered but its button is not covered, the pair is kept
      and the fastener bbox is kept unchanged. This is intentional: the target
      remains supervised even though the visual evidence is occluded.
    - The `visible` field is not used for decisions.
    """

    def __init__(
        self,
        p: float = 0.3,
        target_fastener_types: tuple[str, ...] | None = ("velcro",),
        min_width: float = 0.08,
        max_width: float = 0.35,
        min_height: float = 0.08,
        max_height: float = 0.35,
        max_masks: int = 1,
        button_remove_mode: str = "center",  # "center" or "overlap"
        min_button_overlap: float = 0.75,
        fill_mode: str = "random_gray",     # "random_gray" or "constant"
        fill=(0, 0, 0),
        max_trials: int = 20,
    ):
        super().__init__()

        self.p = p
        self.target_fastener_types = target_fastener_types

        self.min_width = min_width
        self.max_width = max_width
        self.min_height = min_height
        self.max_height = max_height

        self.max_masks = max(1, int(max_masks))

        self.button_remove_mode = button_remove_mode
        self.min_button_overlap = min_button_overlap

        self.fill_mode = fill_mode
        self.fill = fill

        self.max_trials = max(1, int(max_trials))

        if self.min_width <= 0.0 or self.max_width <= 0.0:
            raise ValueError("min_width and max_width must be positive")
        if self.min_height <= 0.0 or self.max_height <= 0.0:
            raise ValueError("min_height and max_height must be positive")
        if self.min_width > self.max_width:
            raise ValueError("min_width must be <= max_width")
        if self.min_height > self.max_height:
            raise ValueError("min_height must be <= max_height")
        if button_remove_mode not in {"center", "overlap"}:
            raise ValueError("button_remove_mode must be 'center' or 'overlap'")
        if fill_mode not in {"random_gray", "constant"}:
            raise ValueError("fill_mode must be 'random_gray' or 'constant'")

    def _is_target_fastener(self, pair) -> bool:
        return True

    def _make_fill(self, image: Image.Image):
        if self.fill_mode == "constant":
            return _coerce_fill(image, self.fill)

        value = random.randint(0, 160)
        return _coerce_fill(image, value)

    def _bbox_to_pixel_xyxy(
        self,
        bbox,
        W: int,
        H: int,
    ) -> tuple[float, float, float, float]:
        x1, y1, x2, y2 = _bbox_to_xyxy(bbox)
        return x1 * W, y1 * H, x2 * W, y2 * H

    def _rect_area(
        self,
        rect: tuple[float, float, float, float],
    ) -> float:
        x1, y1, x2, y2 = rect

        if x1 > x2:
            x1, x2 = x2, x1
        if y1 > y2:
            y1, y2 = y2, y1

        return max(0.0, x2 - x1) * max(0.0, y2 - y1)

    def _intersection_area(
        self,
        a: tuple[float, float, float, float],
        b: tuple[float, float, float, float],
    ) -> float:
        ax1, ay1, ax2, ay2 = a
        bx1, by1, bx2, by2 = b

        if ax1 > ax2:
            ax1, ax2 = ax2, ax1
        if ay1 > ay2:
            ay1, ay2 = ay2, ay1
        if bx1 > bx2:
            bx1, bx2 = bx2, bx1
        if by1 > by2:
            by1, by2 = by2, by1

        ix1 = max(ax1, bx1)
        iy1 = max(ay1, by1)
        ix2 = min(ax2, bx2)
        iy2 = min(ay2, by2)

        return max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)

    def _button_is_made_invisible(
        self,
        button_bbox,
        mask_rect: tuple[float, float, float, float],
        W: int,
        H: int,
    ) -> bool:
        """
        Decide whether a masked region makes a button unusable.

        "center" mode matches the earlier RandomButtonErasing behavior:
        if the button center is inside the erased region, remove the pair.

        "overlap" mode removes the pair only if a sufficiently large fraction
        of the button bbox is masked.
        """
        if self.button_remove_mode == "center":
            point = (
                button_bbox.cx * W,
                button_bbox.cy * H,
            )
            return _rect_contains_point(point, mask_rect)

        button_rect = self._bbox_to_pixel_xyxy(button_bbox, W, H)
        button_area = self._rect_area(button_rect)

        if button_area <= 0.0:
            return False

        overlap = self._intersection_area(button_rect, mask_rect)
        overlap_fraction = overlap / button_area

        return overlap_fraction >= self.min_button_overlap

    def _sample_mask_around_fastener(
        self,
        fastener_bbox,
        W: int,
        H: int,
    ) -> tuple[int, int, int, int]:
        """
        Build a random mask rectangle guaranteed to contain the selected
        fastener center.
        """
        fx = fastener_bbox.cx * W
        fy = fastener_bbox.cy * H

        mask_w = random.uniform(self.min_width, self.max_width) * W
        mask_h = random.uniform(self.min_height, self.max_height) * H

        mask_w = max(1, min(int(round(mask_w)), W))
        mask_h = max(1, min(int(round(mask_h)), H))

        # Randomize the fastener position inside the mask, while ensuring the
        # mask still contains the fastener center.
        local_x = random.uniform(0.2, 0.8) * mask_w
        local_y = random.uniform(0.2, 0.8) * mask_h

        x1 = int(round(fx - local_x))
        y1 = int(round(fy - local_y))

        x1 = max(0, min(x1, W - mask_w))
        y1 = max(0, min(y1, H - mask_h))

        x2 = x1 + mask_w
        y2 = y1 + mask_h

        return x1, y1, x2, y2

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        new_labels = _clone_annotation(labels)

        if random.random() > self.p:
            return image, new_labels

        candidate_pairs = [
            pair
            for pair in new_labels.cloth.pairs
            if self._is_target_fastener(pair)
        ]

        if len(candidate_pairs) == 0:
            return image, new_labels

        W, H = image.size
        out = image.copy()
        draw = ImageDraw.Draw(out)

        n_masks = random.randint(1, self.max_masks)
        mask_rects: list[tuple[int, int, int, int]] = []

        for _ in range(n_masks):
            selected_pair = random.choice(candidate_pairs)

            for _trial in range(self.max_trials):
                mask_rect = self._sample_mask_around_fastener(
                    selected_pair.fastener.bbox,
                    W,
                    H,
                )

                # This is normally guaranteed by construction, but keep the
                # check explicit because the image boundary clamp can move the
                # mask.
                fastener_center = (
                    selected_pair.fastener.bbox.cx * W,
                    selected_pair.fastener.bbox.cy * H,
                )

                if _rect_contains_point(fastener_center, mask_rect):
                    mask_rects.append(mask_rect)
                    draw.rectangle(mask_rect, fill=self._make_fill(image))
                    break

        if len(mask_rects) == 0:
            return image, new_labels

        kept_pairs = []

        for pair in new_labels.cloth.pairs:
            button_removed = any(
                self._button_is_made_invisible(
                    pair.button.bbox,
                    mask_rect,
                    W,
                    H,
                )
                for mask_rect in mask_rects
            )

            if button_removed:
                # If the button is made invisible, remove the whole pair.
                continue

            # If the fastener is masked but the button remains visible, keep
            # the pair unchanged. This is exactly the occlusion-learning case.
            kept_pairs.append(pair)

        new_labels.cloth.pairs = kept_pairs

        return out, new_labels
    

class RandomQuarterTurn(Transform):
    """
    Randomly rotate the image by either +90° or -90°.

    Pillow's ROTATE_90 corresponds to a 90° counter-clockwise rotation.
    ROTATE_270 corresponds to a 90° clockwise rotation.

    The output dimensions are swapped:
        (W, H) -> (H, W)

    Bounding boxes remain normalized in cx, cy, w, h format.
    """

    def __init__(self, p: float = 0.5):
        super().__init__()
        self.p = p

    def __call__(
        self,
        image: Image.Image,
        labels: Annotation,
    ) -> tuple[Image.Image, Annotation]:
        if random.random() >= self.p:
            return image, _clone_annotation(labels)

        rotate_counter_clockwise = random.choice((True, False))

        if rotate_counter_clockwise:
            rotated = image.transpose(_ROTATE_90)

            def transform_bbox(bbox):
                """
                For a +90° counter-clockwise rotation:

                    x' = y
                    y' = 1 - x
                """
                x1, y1, x2, y2 = _bbox_to_xyxy(bbox)

                return (
                    y1,
                    1.0 - x2,
                    y2,
                    1.0 - x1,
                )

        else:
            rotated = image.transpose(_ROTATE_270)

            def transform_bbox(bbox):
                """
                For a -90° clockwise rotation:

                    x' = 1 - y
                    y' = x
                """
                x1, y1, x2, y2 = _bbox_to_xyxy(bbox)

                return (
                    1.0 - y2,
                    x1,
                    1.0 - y1,
                    x2,
                )

        new_labels = _transform_annotation_boxes(labels, transform_bbox)
        return rotated, new_labels