"""
This file was generated by ChatGPT-Astra-Light.
It was prompted to generate the inverse script of the cvattodataset.py script.
"""

import argparse
import json
import xml.etree.ElementTree as xml
from pathlib import Path
import shutil
import dataformat as df


def add_box(
    image: xml.Element,
    label: str,
    bbox: df.BoundingBox,
    visible: bool,
    pair_id: int,
    width: int,
    height: int,
):
    # Convert normalized corner coordinates into pixel coordinates.
    x1, y1, x2, y2 = bbox.to_x1y1x2y2()

    box = xml.SubElement(
        image,
        "box",
        {
            "label": label,
            "source": "manual",
            "occluded": "0",
            "xtl": str(x1 * width),
            "ytl": str(y1 * height),
            "xbr": str(x2 * width),
            "ybr": str(y2 * height),
            "z_order": "0",
        },
    )

    xml.SubElement(box, "attribute", name="pair_id").text = str(pair_id)
    xml.SubElement(box, "attribute", name="visible").text = (
        "true" if visible else "false"
    )


def convert_dataset_to_cvat_xml(dataset_dir, output_xml):
    dataset_dir = Path(dataset_dir)
    output_xml = Path(output_xml)
    annotations_dir = dataset_dir / "annotations"
    images_dir = dataset_dir / "images"

    if not annotations_dir.is_dir():
        raise FileNotFoundError(f"Annotations directory not found: {annotations_dir}")
    if not images_dir.is_dir():
        raise FileNotFoundError(f"Images directory not found: {images_dir}")

    annotation_paths = sorted(annotations_dir.glob("*.json"))
    if not annotation_paths:
        raise ValueError(f"No JSON annotations found in {annotations_dir}")

    root = xml.Element("annotations")
    xml.SubElement(root, "version").text = "1.1"
    image_names = set()

    for image_id, annotation_path in enumerate(annotation_paths):
        try:
            with annotation_path.open(encoding="utf-8") as file:
                annotation = df.Annotation.from_json(json.load(file))

            info = annotation.image
            if info.width <= 0 or info.height <= 0:
                raise ValueError("Image dimensions must be positive.")

            if info.url in image_names:
                raise ValueError(f"Duplicate image name: {info.url}")
            image_names.add(info.url)

            image_path = images_dir / info.url
            if not image_path.is_file():
                raise FileNotFoundError(f"Image not found: {image_path}")

            image = xml.SubElement(
                root,
                "image",
                {
                    "id": str(image_id),
                    "name": info.url,
                    "width": str(info.width),
                    "height": str(info.height),
                },
            )

            for pair_id, pair in enumerate(annotation.cloth.pairs):
                add_box(
                    image=image,
                    label="button",
                    bbox=pair.button.bbox,
                    visible=pair.button.visible,
                    pair_id=pair_id,
                    width=info.width,
                    height=info.height,
                )
                add_box(
                    image=image,
                    label="counterpart",
                    bbox=pair.fastener.bbox,
                    visible=pair.fastener.visible,
                    pair_id=pair_id,
                    width=info.width,
                    height=info.height,
                )

        except Exception as error:
            raise RuntimeError(
                f"Failed to convert {annotation_path}: {error}"
            ) from error

    # Write only after every annotation has been converted successfully.
    output_xml.parent.mkdir(parents=True, exist_ok=True)
    tree = xml.ElementTree(root)
    xml.indent(tree, space="  ")
    tree.write(output_xml, encoding="utf-8", xml_declaration=True)
    # Copy images alongside the XML, preserving any subdirectories.
    output_images_dir = output_xml.parent / "images"
    for image_name in sorted(image_names):
        source = images_dir / image_name
        destination = output_images_dir / image_name
        destination.parent.mkdir(parents=True, exist_ok=True)
        if source.resolve() != destination.resolve():
            shutil.copy2(source, destination)

    print(f"Successfully converted {len(annotation_paths)} images to {output_xml}.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert a custom dataset to CVAT for images XML."
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        required=True,
        help="Dataset directory containing images/ and annotations/.",
    )
    parser.add_argument(
        "--output-xml",
        type=Path,
        required=True,
        help="Destination CVAT XML file.",
    )
    args = parser.parse_args()

    convert_dataset_to_cvat_xml(args.dataset_dir, args.output_xml)